version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm install

      - run:
          command: |
            cd frontend
            npm run build
  test-frondend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm install

      - run:
          command: |
            cd frontend
            npm run test
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd backend
            npm install

      - run:
          command: |
            cd backend
            npm run build
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd backend
            npm install
      - run:
          command: |
            cd backend
            npm run test
  audit-check-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm audit fix --audit-level=critical --force
  audit-check-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd backend
            npm audit fix --audit-level=critical --force 
  create_infrastructure_backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name backend
              --region us-east-2
  create_infrastructure_cloudfront:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure cloudfront infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/cloudfront.yml \
              --stack-name cloudfront  
  create_infrastructure_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure frontend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name my-stack3 
  create_infrastructure_network:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure network infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/network.yml \
              --stack-name my-stack4                           
workflows:
  default:
    jobs:
      - build-frontend
      - test-frondend:
          requires:
            - build-frontend
      - build-backend:
          requires:
            - test-frondend
      - test-backend:
          requires:
            - build-backend
      - audit-check-frontend:
          requires:
            - test-backend
      - audit-check-backend:
          requires:
            - audit-check-frontend
      - create_infrastructure_backend
      - create_infrastructure_cloudfront
      - create_infrastructure_frontend
      - create_infrastructure_network
