version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm install

      - run:
          command: |
            cd frontend
            npm run build
  test-frondend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm install

      - run:
          command: |
            cd frontend
            npm run test
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd backend
            npm install

      - run:
          command: |
            cd backend
            npm run build
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd backend
            npm install
      - run:
          command: |
            cd backend
            npm run test
  audit-check-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm audit --audit-level=critical
  audit-check-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd backend
            npm audit --audit-level=critical                   
workflows:
  default:
    jobs:
      - build-frontend
      - test-frondend:
          requires:
            - build-frontend
      - build-backend:
          requires:
            - test-frondend
      - test-backend:
          requires:
            - build-backend
      - audit-check-frontend:
          requires:
            - test-backend
      - audit-check-backend:
          requires:
            - audit-check-frontend
